apiVersion: v1
kind: Service
metadata:
  name: {{ include "sinch.cc2022.smppdemo.client.name" . }}
  labels:
{{ include "sinch.cc2022.smppdemo.client.labels" .  | indent 4}}
  {{- with .Values.client.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "sinch.cc2022.smppdemo.client.name" . }}
  ports:
    - name: http
      port: 80
      targetPort: http
  type: ClusterIP

