apiVersion: v1
kind: Service
metadata:
  name: {{ include "sinch.cc2022.smppdemo.server.name" . }}
  labels:
{{ include "sinch.cc2022.smppdemo.server.labels" .  | indent 4}}
  {{- with .Values.server.service.annotations }}
  annotations:
{{ toYaml . | indent 4 }}
  {{- end }}
spec:
  selector:
    app.kubernetes.io/name: {{ template "sinch.cc2022.smppdemo.server.name" . }}
  ports:
    - name: smpp
      port: 3601
      targetPort: smpp
  type: ClusterIP

